version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: marketplace-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketplace
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: marketplace-phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: