spring:
  # Database Configuration
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:marketplace}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:false}
        dialect: org.hibernate.dialect.MySQL8Dialect

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: ${FILE_MAX_SIZE:10MB}
      max-request-size: ${FILE_MAX_SIZE:10MB}

  cache:
    cache-names: users, userStats
    caffeine:
      spec: maximumSize=500,expireAfterWrite=60m

  # Mail Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"
            protocols: TLSv1.2
        transport:
          protocol: smtp
        debug: ${MAIL_DEBUG:false}

  # Thymeleaf Configuration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

# Application Specific Configuration
app:
  # Email Settings
  email:
    from: ${APP_EMAIL_FROM}
    support: ${APP_EMAIL_SUPPORT}

  # Frontend URL
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}

  # Social Media Links
  social:
    facebook: ${SOCIAL_FACEBOOK:https://facebook.com/yourmarketplace}
    twitter: ${SOCIAL_TWITTER:https://twitter.com/yourmarketplace}
    instagram: ${SOCIAL_INSTAGRAM:https://instagram.com/yourmarketplace}

  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET}
    expiration-in-ms: ${JWT_EXPIRATION:86400000}

  token:
    verification:
      expiration-minutes: ${VERIFICATION_EXPIRATION:1440}
    password-reset:
      expiration-minutes: ${PASSWORD_RESET_EXPIRATION:30}



  # File Storage Configuration
  file-storage:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}
    max-file-size: ${FILE_MAX_SIZE:5242880}
    allowed-extensions:
      - .jpg
      - .jpeg
      - .png
      - .gif

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: marketplace-platform

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: ${INCLUDE_MESSAGE:never}
    include-binding-errors: ${INCLUDE_BINDING_ERRORS:never}

firebase:
  storage:
    bucket: ${FIREBASE_STORAGE_BUCKET}
  config:
    path: ${FIREBASE_CONFIG_PATH}

# Logging Configuration
logging:
  level:
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}
    com.marketplace: ${LOG_LEVEL_APP:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:INFO}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_SQL_PARAMS:INFO}
    org.springframework.mail: ${LOG_LEVEL_MAIL:INFO}