spring:
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/marketplace?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: exotelhotel2@gmail.com
    password: kvyrkigwoxvsltpw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"
            protocols: TLSv1.2
        transport:
          protocol: smtp
        debug: true

  # Thymeleaf Configuration
  thymeleaf:    # Moved out of mail properties
    prefix: classpath:/templates/
    suffix: .html
    cache: false

# Application Specific Configuration
app:
  # Email Settings
  email:
    from: exotelhotel2@gmail.com
    support: exotelhotel2@gmail.com

  # Frontend URL
  frontend:
    url: http://localhost:3000

  # Social Media Links
  social:
    facebook: https://facebook.com/yourmarketplace
    twitter: https://twitter.com/yourmarketplace
    instagram: https://instagram.com/yourmarketplace

  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET:ABC1234}
    expiration-in-ms: 86400000  # 24 hours

  # File Storage Configuration
  file-storage:
    upload-dir: ./uploads
    max-file-size: 5242880  # 5MB in bytes
    allowed-extensions:
      - .jpg
      - .jpeg
      - .png
      - .gif

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Logging Configuration
logging:
  level:
    org.springframework.security: DEBUG
    com.marketplace: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.mail: DEBUG